# Generated by Django 5.2.3 on 2025-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0002_telegramuser_created_at_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150),
            preserve_default=False,
        ),
    ]
