# Generated by Django 5.2.3 on 2025-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_remove_telegramuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150),
        ),
    ]
