# Generated by Django 5.2.3 on 2025-06-15 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0004_alter_telegramuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
